# Generated by Django 2.2.1 on 2019-05-31 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
