# Generated by Django 2.2.1 on 2019-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainforest', '0003_review_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
